### ISSUE TITLE
Extracting all candidate scores for the CEA task.

### ISSUE THREAD

**Issue by Yansera** [UB-Mannheim/bbw#8]
Dear authors,

Thank you for developing this system, we wanted to try to capture all the candidates and the scores they were given when we applied it. We have therefore made these changes in the following link
https://github.com/Yansera/bbw_scoring_extractor/tree/main/BaselineBBW

These modifications include:
1. line 1143: store the scores of all candidate entities.
2. line 1228: Return all candidate entities directly.

Could you please verify that our changes are correct and that the final output is mapped?

Thanks in advance

**Comment by shigapov** [comment]
We choose simply the most frequent candidate, see [L1140-L1141](https://github.com/UB-Mannheim/bbw/blob/main/bbw/bbw.py#L1140-L1141). So our "scores" are the number of times a candidate appears in the results of different matching algorithms.

If you need more than two candidates, then replace "2" by a bigger number in [L1141](https://github.com/Yansera/bbw_scoring_extractor/blob/main/BaselineBBW/bbw.py#L1141).

**Comment by Yansera** [comment]
Thanks for your answer and explication.
